### SIGNUP
POST http://localhost:3456/auth/signup
content-type: application/json

{
  "email": "testSession@email.com",
  "password": "1234qwer"
}

### SIGNIN
POST http://localhost:3456/auth/signin
content-type: application/json

{
  "email": "testSession@email.com",
  "password": "1234qwer"
}

### SIGNOUT
POST http://localhost:3456/auth/signout
content-type: application/json

{
  "email": "testSession@email.com",
  "password": "1234qwer"
}

### Find user by ID
GET http://localhost:3456/auth/3

### Find users with provided email
GET http://localhost:3456/auth/?email=god@example.com

### Delete user with ID
DELETE http://localhost:3456/auth/4

### Update user
PATCH http://localhost:3456/auth/3
Content-Type: application/json

{
  "email": "newemail@test.com",
  "password": "3333333333"
}

### Set a color
GET http://localhost:3456/auth/colors/red

### Get color
GET http://localhost:3456/auth/colors

### Get currently signed user
GET http://localhost:3456/auth/whoami
